apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.ports }}
    - port: {{  $port }}
      targetPort: {{ $name}}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
